version: "3.9"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: kuantokusta
      POSTGRES_USER: kuantokusta
    networks:
      - kuantokusta
    ports:
      - "12545:5432"
      
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: kuantokusta
    networks:
      - kuantokusta
    ports:
      - "27025:27017"

  products:
    build:
      context: ./products-service
    environment:
      MONGODB_HOST: mongodb
      MONGO_MAPPED_PORT: 27025
      MONGODB_USER: root
      MONGODB_PASSWORD: kuantokusta
      MONGODB_DATABASE: kuantokusta
      PORT: 10421

    networks:
      - kuantokusta
    depends_on:
      - postgres

  shoppingcart:
    build:
      context: ./shopping-cart-service
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_MAPPED_PORT: 12545
      POSTGRES_USER: kuantokusta
      POSTGRES_PASSWORD: kuantokusta
      POSTGRES_DB: kuantokusta
      PRODUCTS_DNS: products
      PORT: 10422
    networks:
      - kuantokusta
    depends_on:
      - mongodb
      - products

  api:
    build:
      context: ./api
    environment:
      PRODUCTS_DNS: products
      SHOPPING_CART_DNS: shoppingcart
      JWT_SECRET: 'JWT-Secret-Sample'
      PORT: 10421

    networks:
      - kuantokusta
    depends_on:
      - products
      - shoppingcart
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: kuantokusta
      PGADMIN_LISTEN_PORT: 15020
    networks:
      - kuantokusta
    depends_on:
      - postgres
    ports:
      - "15020:15020"

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: kuantokusta
    depends_on:
      - mongodb
    networks:
      - kuantokusta
    ports:
      - "18085:8081"


networks:
  kuantokusta:
    driver: bridge